"""Build the self-contained Phosphor icon pack for OutSystems 11.

WHY THIS EXISTS. ODC loads Phosphor 2.0 on every page for free — the platform
host serves Phosphor-Regular.css + Phosphor-IconSizes.css, 1,530 icons, and
that is what compat/neo-phosphor-bridge.css leans on, so the Neo `Icon` block
can emit `<i class="ph ph-cube pds-icon icon-small">` and simply work.

O11 does NOT do that. Drop the same markup into an O11 app and you get nothing
at all: no font, no glyphs, blank space. So an O11 consumer has to ship the
font itself, which is what this script assembles.

SOURCE. @phosphor-icons/web, pinned to a version, fetched from jsDelivr. The
Regular weight yields exactly 1,530 icon classes, matching the count ODC's own
built-in Phosphor exposes — that match is the evidence the two render the same
artwork, so ODC and O11 stay visually identical.

Phosphor Icons is MIT licensed, so redistributing the font inside a theme is
fine; the LICENSE is copied into the pack alongside it.

OUTPUT (dist/o11-phosphor/):
  Phosphor.woff2              the font
  phosphor-icons.css          references the font by URL — needs the woff2
                              uploaded as a module Resource
  phosphor-icons-embedded.css the same CSS with the font inlined as base64 —
                              one file, nothing else to upload
  LICENSE                     Phosphor's MIT licence
  README-o11-import.md        Service Studio steps for both routes

Run: python3 tools/phosphor_o11.py
Requires network access (curl).
"""
import base64
import os
import re
import subprocess
import sys
from datetime import date

VERSION = '2.1.2'
BASE = 'https://cdn.jsdelivr.net/npm/@phosphor-icons/web@{}'.format(VERSION)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'dist', 'o11-phosphor')

# The size helpers. Deliberately NOT named .icon-small / .pds-icon: those are
# ODC portal class names and would collide inside an O11 app that also uses
# OutSystems UI. Explicit pixel names cannot clash with anything.
SIZES = ((16, 'ph-16'), (20, 'ph-20'), (24, 'ph-24'), (32, 'ph-32'))


def fetch(path):
    url = BASE + path
    r = subprocess.run(['curl', '-fsS', '-m', '60', url], capture_output=True)
    if r.returncode != 0:
        sys.exit('fetch failed: {}\n{}'.format(url, r.stderr.decode()[:300]))
    return r.stdout


def main():
    os.makedirs(OUT, exist_ok=True)

    woff2 = fetch('/src/regular/Phosphor.woff2')
    css = fetch('/src/regular/style.css').decode('utf-8')
    licence = fetch('/LICENSE').decode('utf-8')

    if woff2[:4] != b'wOF2':
        sys.exit('Phosphor.woff2 is not a woff2 file (bad magic)')

    names = sorted(set(re.findall(r'^\.ph\.ph-([a-z0-9-]+):before', css, re.M)))
    if not names:
        sys.exit('found no icon rules in style.css — upstream layout changed?')

    # Keep everything from the `.ph` base rule onwards; we replace the
    # @font-face ourselves because we only ship woff2 (the other three formats
    # exist upstream for browsers no O11 app still supports).
    body_at = css.index('.ph {')
    body = css[body_at:].strip()

    header = (
        '/* ==========================================================================\n'
        '   Phosphor icons for OutSystems 11 — Regular weight\n'
        '   --------------------------------------------------------------------------\n'
        '   GENERATED by tools/phosphor_o11.py — do not hand-edit.\n'
        '\n'
        '   Source : @phosphor-icons/web@{version} (Regular)\n'
        '   Icons  : {count} classes, matching the count ODC\'s built-in Phosphor\n'
        '            exposes — so ODC and O11 render the same artwork.\n'
        '   Licence: MIT (see LICENSE in this folder)\n'
        '   Built  : {built}\n'
        '\n'
        '   Usage:  <span class="ph ph-cube ph-20"></span>\n'
        '\n'
        '   ODC needs none of this — the platform host already serves Phosphor there.\n'
        '   This exists purely because O11 does not, so an O11 app must ship the font.\n'
        '   ========================================================================== */\n\n'
    ).format(version=VERSION, count=len(names), built=date.today().isoformat())

    sizes_css = '\n\n/* ---- size helpers ------------------------------------------------------\n' \
                '   A font icon is sized by font-size; width/height do nothing to a glyph.\n' \
                '   Names are pixel-explicit so they cannot collide with OutSystems UI.\n' \
                '   ---------------------------------------------------------------------- */\n'
    for px, cls in SIZES:
        sizes_css += '\n.ph.{cls} {{\n  font-size: {px}px;\n}}\n'.format(cls=cls, px=px)

    # ---- the O11 collision -------------------------------------------------
    # OutSystems UI uses `.ph` to mean *placeholder* and ships
    #     .ph:empty, .placeholder-empty:empty { display: none }
    # to collapse placeholders nobody filled in. Phosphor's base class is also
    # `.ph`, and a font icon is empty by design (the glyph comes from ::before),
    # so that rule hides every icon on the page — silently, at 0x0, with the
    # font loaded and the codepoint correct. MEASURED on a live O11 app: 45 of
    # 45 icons display:none, 0 visible; with the override below, 45 visible at
    # 16x16 and no OutSystems UI placeholder wrongly revealed.
    #
    # Specificity (0,3,0) beats OutSystems UI's (0,2,0), so this wins whichever
    # order the two stylesheets happen to load in. The attribute selectors
    # restrict it to elements that actually carry a `ph-<name>` glyph class, so
    # a genuine bare `.ph` placeholder stays hidden.
    #
    # ODC needs none of this: there `.ph` belongs to Phosphor, which is why
    # tools/neobase.py renames the portal's placeholder `.ph` to `.neo-ph`.
    collision_css = (
        '\n\n/* ---- OutSystems UI collision -------------------------------------------\n'
        '   OutSystems UI hides empty placeholders with\n'
        '     .ph:empty, .placeholder-empty:empty { display: none }\n'
        '   and its `.ph` means *placeholder*, not Phosphor. A font icon is empty\n'
        '   by design, so without this override every icon is hidden at 0x0 with\n'
        '   no console error. Specificity (0,3,0) wins regardless of load order;\n'
        '   the attribute match keeps real placeholders hidden.\n'
        '   ---------------------------------------------------------------------- */\n'
        '\n.ph[class*=" ph-"]:empty,\n.ph[class^="ph-"]:empty {\n'
        '  display: inline-block;\n}\n'
    )

    face_url = (
        '@font-face {\n'
        '  font-family: "Phosphor";\n'
        '  src: url("/PhosphorIcons/Phosphor.woff2") format("woff2");\n'
        '  font-weight: normal;\n'
        '  font-style: normal;\n'
        '  font-display: block;\n'
        '}\n\n'
    )
    face_embedded = (
        '@font-face {{\n'
        '  font-family: "Phosphor";\n'
        '  src: url("data:font/woff2;base64,{b64}") format("woff2");\n'
        '  font-weight: normal;\n'
        '  font-style: normal;\n'
        '  font-display: block;\n'
        '}}\n\n'
    ).format(b64=base64.b64encode(woff2).decode('ascii'))

    # ODC libraries serve a Resource under the library's own path. Same shape as
    # the O11 variant, different prefix — kept separate so neither file has a
    # URL that is wrong for the platform it is pasted into.
    face_odc = (
        '@font-face {\n'
        '  font-family: "Phosphor";\n'
        '  src: url("/NeoPhosphor/Phosphor.woff2") format("woff2");\n'
        '  font-weight: normal;\n'
        '  font-style: normal;\n'
        '  font-display: block;\n'
        '}\n\n'
    )

    linked = header + face_url + body + sizes_css + collision_css
    embedded = (header.replace('Regular weight', 'Regular weight (font embedded)')
                + face_embedded + body + sizes_css + collision_css)
    odc = (header.replace('for OutSystems 11', 'for the NeoPhosphor ODC library')
           + face_odc + body + sizes_css + collision_css)

    write(os.path.join(OUT, 'Phosphor.woff2'), woff2, binary=True)
    write(os.path.join(OUT, 'phosphor-icons.css'), linked)
    write(os.path.join(OUT, 'phosphor-icons-embedded.css'), embedded)
    write(os.path.join(OUT, 'phosphor-icons-odc-library.css'), odc)
    write(os.path.join(OUT, 'LICENSE'), licence)
    write(os.path.join(OUT, 'icon-names.txt'), '\n'.join(names) + '\n')
    write(os.path.join(OUT, 'README-o11-import.md'), readme(names, len(embedded)))

    print('o11 phosphor pack -> dist/o11-phosphor/')
    print('  icons                       : {}'.format(len(names)))
    print('  Phosphor.woff2              : {:,} bytes'.format(len(woff2)))
    print('  phosphor-icons.css          : {:,} bytes'.format(len(linked)))
    print('  phosphor-icons-embedded.css : {:,} bytes'.format(len(embedded)))
    print('  phosphor-icons-odc-library  : {:,} bytes'.format(len(odc)))
    print('  first / last icon           : {} / {}'.format(names[0], names[-1]))


def write(path, data, binary=False):
    mode = 'wb' if binary else 'w'
    kwargs = {} if binary else {'encoding': 'utf-8'}
    with open(path, mode, **kwargs) as fh:
        fh.write(data)


def readme(names, embedded_len):
    return """# Phosphor icons in OutSystems 11

Regular weight, {count} icons, from `@phosphor-icons/web@{version}`. MIT licensed
(see `LICENSE`). Generated by `tools/phosphor_o11.py`.

## READ FIRST — which file to paste where

| Target | File | Resource needed? |
|---|---|---|
| **NeoPhosphor ODC library** | `phosphor-icons-embedded.css` | **No** |
| O11 theme, simplest | `phosphor-icons-embedded.css` | No |
| O11 theme, smaller CSS | `phosphor-icons.css` | Yes, + check the URL |
| ~~ODC library via Resource~~ | ~~`phosphor-icons-odc-library.css`~~ | **Does not work — see below** |

**Do not use `phosphor-icons-odc-library.css`.** It was written on the assumption
that an ODC library Resource is served at `/<LibraryName>/<filename>`. It is not.
Measured on a live ODC page, the platform's own Phosphor font resolves to

    url("../fonts/<HASH>.woff2?<HASH>")

— a hashed, relative path that ODC generates at publish time. ODC rewrites asset
references that are in an *authoring* form (an Image widget's path, for example),
but CSS pasted into a theme is passed through untouched, so a hand-written
absolute URL stays exactly as written and 404s. That failure is silent: boxes or
blank space, no console error.

For an ODC library, use `phosphor-icons-embedded.css`. The font travels inside the
CSS as base64, so there is no Resource, no path, and nothing to get wrong. If you
already added `Phosphor.woff2` as a Resource, it is now unused and can be removed.

## Why this pack exists

ODC serves Phosphor on every page already, so the Neo `Icon` block just emits

    <i class="ph ph-cube pds-icon icon-small"></i>

and it works with no font shipped. **O11 does not do this.** The same markup in
an O11 app renders nothing — no font, no glyph, blank space. So an O11 app has
to carry the font itself. That is all this pack is.

## Two ways to import — pick one

### A. Embedded (simplest — one file, nothing else to upload)

1. Service Studio → your **Theme** → open the stylesheet editor.
2. Paste the whole of `phosphor-icons-embedded.css` at the end.
3. Publish.

The font travels inside the CSS as base64, so there is no Resource to add and
no URL to get wrong. The stylesheet is correspondingly large (~{embedded_kb} KB);
that is the trade you are making for zero setup.

### B. Linked (smaller CSS, font cached separately)

1. In your module, add `Phosphor.woff2` as a **Resource**.
2. Set its **Deploy Action** to `Deploy to Target Directory`.
3. Paste `phosphor-icons.css` into your Theme's stylesheet.
4. Check the `@font-face` URL near the top matches where the resource lands.
   It ships as:

       url("/PhosphorIcons/Phosphor.woff2")

   Replace `PhosphorIcons` with **your module name** if it differs. Getting
   this path wrong is the one failure mode of this route, and it fails
   silently — boxes or blank space, no console error.
5. Publish.

## Using an icon

    <span class="ph ph-cube ph-20"></span>

`ph` loads the font, `ph-<name>` selects the glyph, and the size helper sets
`font-size` — a font icon is sized by `font-size`, not width/height, which is
the single most common mistake when moving from an SVG icon set.

Sizes provided: `ph-16`, `ph-20`, `ph-24`, `ph-32`. Deliberately not named
`icon-small` / `pds-icon`: those are ODC portal class names and would collide
with OutSystems UI inside an O11 app.

Colour follows `color`, since the glyph is text:

    <span class="ph ph-warning ph-24" style="color: red"></span>

## Troubleshooting: the icons are invisible in O11

If every icon is missing — no boxes, no blank squares, just nothing — the cause
is almost certainly **OutSystems UI's `.ph`**. OutSystems UI uses `.ph` to mean
*placeholder* and ships

    .ph:empty, .placeholder-empty:empty {{ display: none }}

to collapse placeholders nobody filled in. Phosphor's base class is also `.ph`,
and a font icon is empty by design (the glyph comes from `::before`), so that
rule hides every icon on the page. It fails silently: the font loads, the
codepoint is right, `document.fonts.check` passes, and every icon is 0x0.

This pack already carries the override that fixes it, at the very end of the
generated CSS:

    .ph[class*=" ph-"]:empty,
    .ph[class^="ph-"]:empty {{ display: inline-block; }}

So if you are seeing this, **your theme has an older paste** — regenerate and
re-paste the whole file. Do not "fix" it by deleting OutSystems UI's rule; real
placeholders depend on it. The override's specificity (0,3,0) beats OutSystems
UI's (0,2,0), so it wins whichever order the stylesheets load in, and the
attribute match means a genuine bare `.ph` placeholder stays hidden.

ODC is not affected. There `.ph` belongs to Phosphor, which is exactly why
`tools/neobase.py` renames the portal's placeholder `.ph` to `.neo-ph`.

## Icon names

All {count} names are in `icon-names.txt`, one per line. Browse them visually at
https://phosphoricons.com (set the weight to Regular).

## Keeping ODC and O11 in step

Both sides are Phosphor Regular 2.x and expose the same {count} classes, so a
name that works in one works in the other. If you ever bump `VERSION` in
`tools/phosphor_o11.py`, re-run it and re-check that count — a change there
means the two platforms have drifted apart.
""".format(count=len(names), version=VERSION,
           embedded_kb=round(embedded_len / 1024))


if __name__ == '__main__':
    main()
